#!/usr/bin/env bash
# nginx startup on server
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World' | sudo tee /var/www/html/index.html
sudo ufw allow 'Nginx HTTP'
sudo service nginx start