#!/usr/bin/env bash
# Installs nginx
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo 'Hello World' | sudo tee /var/www/html/index.html
sudo touch /var/www/html/error404.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/error.html
findit="\tlocation / {"
replace="\terror_page 404 /error404.html;\n\n\tlocation /redirect_me {\n\t\treturn 301 \$scheme:https://youtu.be/OE2NPmqZ9nM;\n\t}\n\n\tlocation / {"
sudo sed -i "s@^$findit@$replace@" /etc/nginx/sites-available/default
sudo service nginx restart                    