#!/usr/bin/env bash
#prints Holberton School using while loop x10 and prints hi on 9th line
i="1"
while [ $i -le 10 ]
        do
	if [ $i -eq 9 ]
	then 
		echo "Holberton School"
		echo "Hi"
	else
		echo "Holberton School"
	fi	
	i=$((i+1))
        done
