#!/usr/bin/env bash
#prints 1-20 replacing for bad luck
for i in {1..20}
do 
	echo "$i"
if [ $i -eq 4 ]
then echo "bad luck from China"
elif [ $i -eq 9 ]
then echo "bad luck from Japan"
elif [ $i -eq 17 ]
then echo "bad luck from Italy"
fi

done
